import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const file=new URL('../supabase/functions/rateware-api/gmail-delivery-evidence.mjs',import.meta.url);
const mod=await import(file.href);
test('provider evidence keeps only status and safe reason codes',()=>{assert.deepEqual(mod.gmailFailureEvidence(403,{error:{message:'secret message',errors:[{reason:'userRateLimitExceeded',token:'secret'},{reason:'secret token with spaces'}],key:'secret'}}),{http_status:403,provider_reason_codes:['userRateLimitExceeded']});});
test('invalid HTTP and malformed reasons cannot escape sanitizer',()=>{assert.deepEqual(mod.gmailFailureEvidence('403',{error:'secret'}),{http_status:null,provider_reason_codes:[]});});
function db(row,error=null){const calls=[];const q={select(x){calls.push(['select',x]);return q},eq(...x){calls.push(['eq',...x]);return q},in(...x){calls.push(['in',...x]);return q},order(...x){calls.push(['order',...x]);return q},limit(...x){calls.push(['limit',...x]);return q},abortSignal(signal){calls.push(['abort',signal instanceof AbortSignal]);return q},async maybeSingle(){return {data:row,error}}};return {calls,from(table){calls.push(['from',table]);return q}};}
const row={outreach_message_id:'m',owner_email:'owner',rfx_event_id:'e',status:'failed',occurred_at:'2026-10-07T00:10:00Z',metadata:{delivery_error:'Precondition check failed.',http_status:400,provider_reason_codes:['failedPrecondition'],access_token:'secret'}};
test('diagnostic read is scoped to owner, message, event and source; no payload secrets returned',async()=>{const d=db(row),r=await mod.readLatestOutreachIssue(d,'owner',{id:'m',rfx_event_id:'e',channel:'email'});assert.ok(d.calls.some(x=>JSON.stringify(x)===JSON.stringify(['eq','owner_email','owner'])));assert.ok(d.calls.some(x=>JSON.stringify(x)===JSON.stringify(['eq','outreach_message_id','m'])));assert.ok(d.calls.some(x=>JSON.stringify(x)===JSON.stringify(['eq','rfx_event_id','e'])));assert.ok(d.calls.some(x=>JSON.stringify(x)===JSON.stringify(['eq','metadata->>source','outreach_send_attempt'])));assert.equal(r.delivery_issue.http_status,400);assert.ok(!JSON.stringify(r).includes('secret'));});
test('foreign diagnostic is rejected even if database returns it',async()=>{assert.equal((await mod.readLatestOutreachIssue(db({...row,owner_email:'foreign'}),'owner',{id:'m',rfx_event_id:'e',channel:'email'})).delivery_issue,null);});
test('failed journal read is explicit and does not throw away the message',async()=>{assert.equal((await mod.readLatestOutreachIssue(db(null,{message:'secret'}),'owner',{id:'m',rfx_event_id:'e',channel:'email'})).delivery_issue_unavailable,true);});
test('legacy failure retains timestamp and text without inventing HTTP',async()=>{const r=await mod.readLatestOutreachIssue(db({...row,metadata:{delivery_error:'Precondition check failed.'}}),'owner',{id:'m',rfx_event_id:'e',channel:'email'});assert.equal(r.delivery_issue.http_status,null);assert.equal(r.delivery_issue.error,'Precondition check failed.');});
