import test from 'node:test';import assert from 'node:assert/strict';
// Lazy import makes an absent capability a named assertion failure before implementation.
let check;async function subject(){try{check??=(await import('../supabase/functions/rateware-api/gmail-connection-check.mjs')).checkGmailConnection;}catch{assert.fail('Gmail profile check is not implemented');}return check;}
const sender='sender@example.test',owner='org:fixture',scopes=['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send'];
function harness(extra={}){const predicates=[],requests=[],credentials=[];const row={owner_email:owner,mailbox_email:sender,status:'connected',scopes,...extra.row};const db={from(table){assert.equal(table,'gmail_mailbox_connections');return{select(fields){assert.equal(fields,'owner_email,mailbox_email,status,scopes');return this;},eq(key,value){predicates.push([key,value]);return this;},abortSignal(signal){assert.ok(signal instanceof AbortSignal);return this;},async maybeSingle(){return extra.dbError?{error:{message:'SECRET DATABASE ERROR'}}:{data:extra.missing?null:row};}};}};
return{predicates,requests,credentials,async run(){return(await subject())({client:db,user:{owner_email:extra.owner??owner},sender,resolveToken:async(c,u,s)=>{assert.equal(c,db);credentials.push([u.owner_email,s]);if(extra.credentialError)throw Error('PRIVATE REFRESH TOKEN');return'PRIVATE_ACCESS_TOKEN';},fetchImpl:async(url,options)=>{requests.push([url,options]);if(extra.transportError)throw Error('PRIVATE TRANSPORT ERROR');return{ok:(extra.status??200)===200,status:extra.status??200,json:async()=>extra.payload??{emailAddress:sender,messagesTotal:50,threadsTotal:20,historyId:'PRIVATE_HISTORY'}};},now:()=>Date.parse('2026-10-08T18:00:00Z')});}};}
test('owner and sender are filtered; one profile GET returns a minimal result without mailbox content or credentials',async()=>{const h=harness(),r=await h.run();assert.deepEqual(h.predicates,[['owner_email',owner],['mailbox_email',sender]]);assert.equal(h.requests.length,1);assert.equal(h.requests[0][0],'https://gmail.googleapis.com/gmail/v1/users/me/profile');assert.equal(h.requests[0][1].method,'GET');assert.equal(h.requests[0][1].redirect,'error');assert.equal(h.requests[0][1].body,undefined);assert.ok(h.requests[0][1].signal instanceof AbortSignal);assert.equal(r.state,'available');assert.equal(r.http_status,200);assert.equal(r.send_scope_granted,true);assert.ok(!/PRIVATE|messagesTotal|threadsTotal|emailAddress/.test(JSON.stringify(r)));});
test('connection absent or foreign never retrieves a token or calls Google',async()=>{for(const options of [{missing:true},{row:{owner_email:'foreign'}},{row:{mailbox_email:'foreign@example.test'}},{row:{status:'error'}},{owner:''}]){const h=harness(options),r=await h.run();assert.equal(r.state,'not_connected');assert.equal(h.credentials.length,0);assert.equal(h.requests.length,0);}});
test('send-only scope cannot check profile; lack of send scope is reported without enlarging permissions',async()=>{const h=harness({row:{scopes:['https://www.googleapis.com/auth/gmail.send']}});assert.equal((await h.run()).state,'scope_missing');assert.equal(h.requests.length,0);const read=harness({row:{scopes:['https://www.googleapis.com/auth/gmail.readonly']}});assert.equal((await read.run()).send_scope_granted,false);});
test('credential failure is bounded to its stage and does not leak exception content',async()=>{const h=harness({credentialError:true}),r=await h.run();assert.equal(r.state,'credentials_unavailable');assert.equal(r.stage,'credentials');assert.equal(h.requests.length,0);assert.ok(!JSON.stringify(r).includes('PRIVATE'));});
test('provider rejection returns allowed reasons and HTTP, without auto retry or raw error body',async()=>{const h=harness({status:403,payload:{error:{message:'PRIVATE MESSAGE',errors:[{reason:'domainPolicy'},{reason:'PRIVATE_REASON'}]}}}),r=await h.run();assert.equal(r.state,'provider_rejected');assert.equal(r.http_status,403);assert.deepEqual(r.reason_codes,['domainPolicy']);assert.equal(h.requests.length,1);assert.ok(!JSON.stringify(r).includes('PRIVATE'));});
test('quota rejection and transport failure never send or retry',async()=>{const q=harness({status:429,payload:{error:{errors:[{reason:'rateLimitExceeded'}]}}});assert.equal((await q.run()).state,'provider_rejected');assert.equal(q.requests.length,1);const lost=harness({transportError:true});assert.equal((await lost.run()).state,'unavailable');assert.equal(lost.requests.length,1);});
test('malformed success or a different Google identity cannot report available',async()=>{for(const payload of [{},{emailAddress:'foreign@example.test'},'PRIVATE RAW']){const h=harness({payload}),r=await h.run();assert.equal(r.state,'identity_unconfirmed');assert.ok(!JSON.stringify(r).includes('foreign'));}});
test('database read failure makes no token or provider calls and hides raw database error',async()=>{const h=harness({dbError:true}),r=await h.run();assert.equal(r.state,'unavailable');assert.equal(r.stage,'stored');assert.equal(h.requests.length,0);assert.equal(h.credentials.length,0);assert.ok(!JSON.stringify(r).includes('SECRET'));});
test('credential timeout ends the check without starting a provider request',async()=>{const h=harness();let fetches=0;const client={from(){return{select(){return this;},eq(){return this;},abortSignal(){return this;},async maybeSingle(){return{data:{owner_email:owner,mailbox_email:sender,status:'connected',scopes}};}};}};const r=await(await subject())({client,user:{owner_email:owner},sender,resolveToken:()=>new Promise(()=>{}),fetchImpl:()=>{fetches++;throw Error('No provider call expected');},timeoutMs:5});assert.equal(r.state,'credentials_unavailable');assert.equal(fetches,0);});
test('provider abort produces an inconclusive result and no second call',async()=>{let calls=0;const client={from(){return{select(){return this;},eq(){return this;},abortSignal(){return this;},async maybeSingle(){return{data:{owner_email:owner,mailbox_email:sender,status:'connected',scopes}};}};}};const keepAlive=setInterval(()=>{},100);try{const r=await(await subject())({client,user:{owner_email:owner},sender,resolveToken:async()=> 'fixture',timeoutMs:5,fetchImpl:(_url,{signal})=>{calls++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('Fixture abort'))));}});assert.equal(r.state,'unavailable');assert.equal(r.stage,'profile');assert.equal(calls,1);}finally{clearInterval(keepAlive);}});
test('the actual server role policy requires operate for this action',async()=>{const fs=await import('node:fs');const {createRequire}=await import('node:module');const {transformSync}=createRequire(import.meta.url)(process.env.ESBUILD_MODULE||'esbuild');const file=process.env.GMAIL_CHECK_ROLES_FILE||new URL('../supabase/functions/_shared/team-roles.ts',import.meta.url);const code=transformSync(fs.readFileSync(file,'utf8'),{loader:'ts',format:'esm'}).code;const roles=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));assert.equal(roles.teamRoleNeed('rateware-api','check_gmail_connection',{}),'operate');for(const role of ['admin','operator'])assert.equal(roles.teamRoleDenial('rateware-api',{rateware_organization_id:'fixture',roles:[role]},{action:'check_gmail_connection'}),null);assert.equal(roles.teamRoleDenial('rateware-api',{rateware_organization_id:'fixture',roles:['viewer']},{action:'check_gmail_connection'}).code,'role_forbidden');});
