import test from 'node:test';import assert from 'node:assert/strict';
let verify;async function subject(){try{verify??=(await import('../supabase/functions/rateware-api/gmail-message-verification.mjs')).verifyOutreachGmailMessage;}catch{assert.fail('Owned Gmail message verification is missing');}return verify;}
const id='00000000-0000-4000-8000-000000000001',event='00000000-0000-4000-8000-000000000002',owner='org:fixture',sender='sender@example.test',receipt='abc123';
function harness(options={}){const filters=[],credentials=[],calls=[];const data={rfx_events:{id:event,owner_email:owner,...options.eventData},outreach_messages:{id,owner_email:owner,rfx_event_id:event,channel:'email',provider:'gmail',provider_message_id:receipt,...options.message},gmail_mailbox_connections:{owner_email:owner,mailbox_email:sender,status:'connected',scopes:['https://www.googleapis.com/auth/gmail.readonly'],...options.connection}};const client={from(table){const query={select(){return query;},eq(key,value){filters.push([table,key,value]);return query;},abortSignal(signal){assert.ok(signal instanceof AbortSignal);return query;},async maybeSingle(){return{data:options.missing===table?null:data[table],error:options.dbError?{message:'PRIVATE DATABASE'}:null};}};return query;}};
return{filters,credentials,calls,async run(){return(await subject())({client,user:{owner_email:options.owner??owner},sender,messageId:options.id??id,eventId:options.event??event,resolveToken:async()=>{credentials.push(1);if(options.credentialError)throw Error('PRIVATE TOKEN ERROR');return'PRIVATE TOKEN';},fetchImpl:async(url,opts)=>{calls.push([url,opts]);if(options.transportError)throw Error('PRIVATE TRANSPORT');return{ok:(options.status??200)===200,status:options.status??200,json:async()=>options.payload??{id:receipt,labelIds:['SENT'],payload:{body:'PRIVATE BODY'},snippet:'PRIVATE SNIPPET'}};},timeoutMs:options.timeoutMs??8000});}};}
test('owned receipt uses one minimal GET and returns only state, time and safe diagnostics',async()=>{const h=harness(),r=await h.run();assert.equal(r.state,'found_sent');assert.equal(r.http_status,200);assert.equal(h.calls.length,1);const url=new URL(h.calls[0][0]);assert.equal(url.hostname,'gmail.googleapis.com');assert.equal(url.pathname,'/gmail/v1/users/me/messages/abc123');assert.equal(url.searchParams.get('format'),'minimal');assert.equal(h.calls[0][1].method,'GET');assert.equal(h.calls[0][1].body,undefined);assert.equal(h.calls[0][1].redirect,'error');assert.ok(!/PRIVATE|payload|snippet|labelIds/.test(JSON.stringify(r)));assert.deepEqual(h.filters.slice(0,5),[['rfx_events','owner_email',owner],['rfx_events','id',event],['outreach_messages','owner_email',owner],['outreach_messages','rfx_event_id',event],['outreach_messages','id',id]]);});
test('foreign event, message or connection stops before retrieving credentials',async()=>{for(const options of[{message:{owner_email:'foreign'}},{message:{id:'foreign'}},{message:{rfx_event_id:'foreign'}},{connection:{owner_email:'foreign'}},{missing:'rfx_events'},{missing:'outreach_messages'},{owner:''},{id:'arbitrary provider id'},{event:'invalid'}]){const h=harness(options),r=await h.run();assert.ok(['missing','not_connected'].includes(r.state));assert.equal(h.credentials.length,0);assert.equal(h.calls.length,0);}});
test('missing, invalid or non-Gmail receipt cannot turn into an arbitrary mailbox lookup',async()=>{for(const message of[{provider_message_id:null},{provider_message_id:'../../private?x=1'},{channel:'whatsapp'},{provider:'different'}]){const h=harness({message});assert.equal((await h.run()).state,'no_receipt');assert.equal(h.calls.length,0);assert.equal(h.credentials.length,0);}});
test('provider found without SENT and malformed identity remain distinct from verified sent',async()=>{for(const[payload,state]of[[{id:receipt,labelIds:['INBOX']},'found_not_sent'],[{id:'foreign',labelIds:['SENT']},'unavailable'],[{id:receipt,labelIds:'SENT'},'unavailable']]){const h=harness({payload});assert.equal((await h.run()).state,state);assert.equal(h.calls.length,1);}});
test('404 and rate/permission errors preserve receipt and never retry',async()=>{for(const[status,state]of[[404,'not_found'],[403,'provider_rejected'],[429,'provider_rejected']]){const h=harness({status,payload:{error:{message:'PRIVATE ERROR',errors:[{reason:'rateLimitExceeded'},{reason:'PRIVATE_REASON'}]}}}),r=await h.run();assert.equal(r.state,state);assert.equal(r.http_status,status);assert.ok(!JSON.stringify(r).includes('PRIVATE'));assert.equal(h.calls.length,1);}});
test('scope, credential, database and transport failures do not leak details',async()=>{for(const[options,state]of[[{connection:{scopes:['https://www.googleapis.com/auth/gmail.send']}},'scope_missing'],[{credentialError:true},'credentials_unavailable'],[{dbError:true},'unavailable'],[{transportError:true},'unavailable']]){const h=harness(options),r=await h.run();assert.equal(r.state,state);assert.ok(!JSON.stringify(r).includes('PRIVATE'));assert.ok(h.calls.length<=1);}});
test('foreign event returned by storage is rejected even when message ownership matches',async()=>{const h=harness({eventData:{owner_email:'foreign'}});assert.equal((await h.run()).state,'missing');assert.equal(h.credentials.length,0);assert.equal(h.calls.length,0);});
test('credential timeout never starts a Google request',async()=>{let calls=0;const client={from(table){return{select(){return this;},eq(){return this;},abortSignal(){return this;},async maybeSingle(){return{data:table==='rfx_events'?{id:event,owner_email:owner}:table==='outreach_messages'?{id,owner_email:owner,rfx_event_id:event,channel:'email',provider_message_id:receipt}:{owner_email:owner,mailbox_email:sender,status:'connected',scopes:['https://www.googleapis.com/auth/gmail.readonly']}};}};}};const r=await(await subject())({client,user:{owner_email:owner},sender,messageId:id,eventId:event,timeoutMs:5,resolveToken:()=>new Promise(()=>{}),fetchImpl:()=>{calls++;throw Error('No request expected');}});assert.equal(r.state,'credentials_unavailable');assert.equal(calls,0);});
test('real server role policy treats verification as an operation, not a Viewer read',async()=>{const fs=await import('node:fs'),{createRequire}=await import('node:module'),{transformSync}=createRequire(import.meta.url)(process.env.ESBUILD_MODULE||'esbuild');const file=process.env.GMAIL_ROLES_FILE||new URL('../supabase/functions/_shared/team-roles.ts',import.meta.url);const code=transformSync(fs.readFileSync(file,'utf8'),{loader:'ts',format:'esm'}).code;const roles=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));assert.equal(roles.teamRoleNeed('rateware-api','verify_outreach_gmail_message',{}),'operate');assert.equal(roles.teamRoleAllows('viewer','operate'),false);assert.equal(roles.teamRoleAllows('operator','operate'),true);});
