import {payloadFingerprint,stableStringify} from '../supabase/functions/_shared/marksman-loads-bid-contract.ts';
import {FIT_RUBRICS,MARKSMAN_LOADS_FIT_REQUEST_VERSION,canBindFitCommandReadback,normalizeFitPayload,verifyMarksmanLoadsFitRequest} from '../supabase/functions/_shared/marksman-loads-fit-contract.ts';

function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(message);}
const SECRET='0123456789abcdef0123456789abcdef',NOW=new Date('2026-09-07T12:00:30.000Z');
const UUID={request:'11111111-1111-4111-8111-111111111111',vendor:'22222222-2222-4222-8222-222222222222',lane:'33333333-3333-4333-8333-333333333333',event:'44444444-4444-4444-8444-444444444444',invitation:'55555555-5555-4555-8555-555555555555'};
const PREPARED_RECEIPT_ID='prepared-fit-01';
const confirmations=()=>FIT_RUBRICS.map(rubric_key=>({segment_key:'dry-van',rubric_key,answer:'agree',comment:''}));
async function sign(unsigned:Record<string,unknown>){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(stableStringify(unsigned))));return[...bytes].map(value=>value.toString(16).padStart(2,'0')).join('');}
async function fixture(payloadValue:unknown={action:'save_segment_confirmations',confirmations:confirmations()}){const payload=normalizeFitPayload(payloadValue),fitPayloadFingerprint=await payloadFingerprint(payload),operationId=await payloadFingerprint({effect:'fit',organizationId:'carrier-org',vendorId:UUID.vendor,eventId:UUID.event,laneId:UUID.lane,invitationId:UUID.invitation,preparedReceiptId:PREPARED_RECEIPT_ID,fitPayloadFingerprint}),unsigned={contractVersion:MARKSMAN_LOADS_FIT_REQUEST_VERSION,issuer:'marksman-loads',audience:'rateware',keyId:'fit-key',requestId:UUID.request,issuedAt:'2026-09-07T12:00:00.000Z',expiresAt:'2026-09-07T12:01:00.000Z',body:{action:'resolve_and_save_fit',organizationId:'carrier-org',vendorId:UUID.vendor,eventId:UUID.event,laneId:UUID.lane,invitationId:UUID.invitation,operationId,preparedReceiptId:PREPARED_RECEIPT_ID,payloadFingerprint:fitPayloadFingerprint,payload,humanConfirmation:{actorId:'operator-1',role:'OPERATOR',confirmedAt:'2026-09-07T12:00:00.000Z'}}};return{...unsigned,signature:await sign(unsigned)};}
async function rejected(envelope:Record<string,unknown>,code:string){let observed='';try{await verifyMarksmanLoadsFitRequest(envelope,{sharedSecret:SECRET,expectedKeyId:'fit-key',now:NOW});}catch(error){observed=(error as{code?:string}).code||'';}assert(observed===code,`expected ${code}, received ${observed}`);}

Deno.test('fit contract requires exactly the six canonical rubrics under one segment',async()=>{const verified=await verifyMarksmanLoadsFitRequest(await fixture(),{sharedSecret:SECRET,expectedKeyId:'fit-key',now:NOW});assert(verified.body.payload.confirmations.length===6,'six answers required');assert(verified.body.payload.confirmations.map(row=>row.rubric_key).join(',')===FIT_RUBRICS.join(','),'rubrics must be canonical');assert(verified.body.payload.confirmations.every(row=>row.segment_key==='dry-van'),'one segment required');});

Deno.test('fit contract accepts the fixed MARKSMAN Loads Node.js vector',async()=>{const envelope=await fixture(),body=envelope.body as Record<string,unknown>;assert(body.payloadFingerprint==='749e1a46c1e0d139c5e04ceb0d856b5267959f5c613e8c45aff3518d820d5f0e','Fit payload fingerprint must match Loads');assert(body.operationId==='ab7e2f42dc59452a4618ed5fb444c17d43b593094d0d35a42e7421bece254054','Fit operation must match Loads');assert(envelope.signature==='672cc58b4551c2dee0c5b7dd4dedb3820f36ff0e0a7b2158d1504e7a3485eee2','Fit HMAC must match Loads');const verified=await verifyMarksmanLoadsFitRequest(envelope,{sharedSecret:SECRET,expectedKeyId:'fit-key',now:NOW});assert(verified.body.operationId===body.operationId,'Rateware must retain the signed Loads Fit operation');});

Deno.test('fit contract rejects missing, duplicate, pending and mixed-segment answers',async()=>{
  for(const payload of [
    {action:'save_segment_confirmations',confirmations:confirmations().slice(0,5)},
    {action:'save_segment_confirmations',confirmations:[...confirmations().slice(0,5),confirmations()[0]]},
    {action:'save_segment_confirmations',confirmations:confirmations().map((row,index)=>index?row:{...row,answer:'pending'})},
    {action:'save_segment_confirmations',confirmations:confirmations().map((row,index)=>index?row:{...row,segment_key:'reefer'})},
  ]){let failed=false;try{normalizeFitPayload(payload);}catch{failed=true;}assert(failed,'invalid six-rubric payload must fail');}
});

Deno.test('conditions require a rubric-specific comment and cannot hide in a general note',()=>{const rows=confirmations();rows[2]={...rows[2],answer:'exception'};let code='';try{normalizeFitPayload({action:'save_segment_confirmations',confirmations:rows});}catch(error){code=(error as{code?:string}).code||'';}assert(code==='FIT_CONDITION_COMMENT_REQUIRED','condition must explain its exact rubric');rows[2].comment='Appointment requires 24 hours notice.';assert(normalizeFitPayload({action:'save_segment_confirmations',confirmations:rows}).confirmations[2].comment.includes('24 hours'),'comment should survive');});

Deno.test('fit envelope rejects tampering and only ADMIN or OPERATOR may authorize',async()=>{const tampered=await fixture();(tampered.body as Record<string,unknown>).operationId='b'.repeat(64);await rejected(tampered,'INVALID_FIT_SIGNATURE');const viewer=await fixture(),body=viewer.body as Record<string,unknown>;body.humanConfirmation={actorId:'viewer',role:'VIEWER',confirmedAt:'2026-09-07T12:00:00.000Z'};const{signature:_old,...unsigned}=viewer;viewer.signature=await sign(unsigned);await rejected(viewer,'HUMAN_CONFIRMATION_REQUIRED');});

Deno.test('fit operation identity is derived from the prepared quote and exact Fit content',async()=>{const valid=await fixture(),verified=await verifyMarksmanLoadsFitRequest(valid,{sharedSecret:SECRET,expectedKeyId:'fit-key',now:NOW});assert(verified.body.preparedReceiptId===PREPARED_RECEIPT_ID,'prepared receipt must survive verification');const mismatched=await fixture(),body=mismatched.body as Record<string,unknown>;body.operationId='a'.repeat(64);const{signature:_old,...unsigned}=mismatched;mismatched.signature=await sign(unsigned);await rejected(mismatched,'OPERATION_ID_MISMATCH');const missing=await fixture(),missingBody=missing.body as Record<string,unknown>;delete missingBody.preparedReceiptId;const{signature:_oldMissing,...missingUnsigned}=missing;missing.signature=await sign(missingUnsigned);await rejected(missing,'INVALID_FIT_REQUEST');});

Deno.test('only persisted returned canonical fit commands may create operation receipts',()=>{const valid={status:'submitted',external_execution:true,rateware_fit_submission:true,result:{canonicalResult:{rows:[{id:'row'}]}}};assert(canBindFitCommandReadback(valid),'returned canonical fit can bind');for(const command of [{...valid,status:'executing'},{...valid,status:'reconcile_required'},{...valid,result:{}},{...valid,rateware_fit_submission:false}])assert(!canBindFitCommandReadback(command),'uncertain fit cannot mint receipt');});
