import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL(path, import.meta.url), "utf8");
const migration = read("../supabase/migrations/20260712160000_shipper_crm.sql");
const commercialMigration = read("../supabase/migrations/20260713173000_shipper_commercial_workflow.sql");
const rfxLinkMigration = read("../supabase/migrations/20260713180000_shipper_opportunity_rfx_link.sql");
const duplicateMigration = read("../supabase/migrations/20260713190000_shipper_duplicate_review.sql");
const actionsMigration = read("../supabase/migrations/20260713200000_shipper_account_actions.sql");
const relationalImportMigration = read("../supabase/migrations/20260713210000_shipper_crm_relational_import.sql");
const api = read("../supabase/functions/rateware-api/index.ts");
const service = read("../src/shipper-service.js");
const rfxService = read("../src/rfx-process-service.js");
const rfxClient = read("../src/rfx-process.js");
const page = read("../shipper-crm.html");
const client = read("../src/shippers.js");
const auth = read("../src/auth.js");
const styles = read("../src/styles.css");

for (const table of ["shippers", "shipper_contacts", "shipper_locations", "shipper_lanes", "shipper_rfis", "shipper_opportunities"]) {
  assert.match(migration, new RegExp(`create table if not exists public\\.${table}`));
  assert.match(migration, new RegExp(`alter table public\\.${table} enable row level security`));
}

assert.match(migration, /lower\(owner_email\) = lower\(coalesce\(auth\.jwt\(\) ->> 'email'/);
assert.match(migration, /auth\.jwt\(\) ->> 'organization_id'/);
assert.doesNotMatch(migration, /using \(true\)/i);
assert.match(migration, /shippers_owner_domain_unique_idx/);

for (const action of ["shipper_crm_summary", "list_shippers", "list_shipper_duplicates", "merge_shipper_accounts", "shipper_relationship_pipeline", "shipper_commercial_work", "shipper_action_queue", "update_shipper_account_action_status", "shipper_intelligence", "promote_shipper_rfi_to_opportunity", "move_shipper_opportunity_stage", "launch_shipper_opportunity_rfx", "get_shipper", "shipper_account_activity", "create_shipper", "import_shippers", "update_shipper", "move_shipper_relationship_stage", "archive_shippers", "save_shipper_record", "delete_shipper_record"]) {
  assert.match(api, new RegExp(`body\\.action === "${action}"`));
  assert.match(service, new RegExp(`"${action}"`));
}

assert.match(commercialMigration, /add column if not exists rfi_id uuid references public\.shipper_rfis/);
assert.match(commercialMigration, /shipper_opportunities_owner_rfi_idx/);
assert.match(commercialMigration, /shipper_opportunities_owner_open_due_idx/);
assert.match(rfxLinkMigration, /add column if not exists rfx_project_id uuid references public\.rfx_projects/);
assert.match(rfxLinkMigration, /shipper_opportunities_owner_rfx_project_unique_idx/);
assert.match(duplicateMigration, /shippers_owner_legal_name_active_idx/);
assert.match(duplicateMigration, /shippers_owner_primary_email_active_idx/);
assert.match(actionsMigration, /create table if not exists public\.shipper_account_actions/);
assert.match(actionsMigration, /alter table public\.shipper_account_actions enable row level security/);
assert.match(actionsMigration, /shipper_account_actions_owner_shipper_idx/);
assert.match(actionsMigration, /status in \('open', 'in_progress', 'done', 'cancelled'\)/);
assert.match(relationalImportMigration, /add column if not exists external_source text/);
assert.match(relationalImportMigration, /add column if not exists external_source_id text/);
assert.match(relationalImportMigration, /shippers_owner_external_source_unique_idx/);
assert.match(relationalImportMigration, /shipper_contacts_owner_external_source_unique_idx/);
assert.match(relationalImportMigration, /shipper_opportunities_owner_external_source_unique_idx/);

assert.match(api, /\.eq\("owner_email", user\.owner_email\)/);
assert.match(api, /requireOwnedShipper/);
assert.match(api, /invalidShipperValue/);
assert.match(api, /invalidShipperChildValue/);
assert.match(api, /applyShipperChildDefaults/);
assert.match(api, /body\.action === "import_shippers"/);
assert.match(api, /body\.action === "import_shipper_crm_workbook"/);
assert.match(api, /normalizeShipperCrmWorkbookAccount/);
assert.match(api, /normalizeShipperCrmWorkbookContact/);
assert.match(api, /normalizeShipperCrmWorkbookOpportunity/);
assert.match(api, /Linked account was not found in this workspace/);
assert.match(api, /shipper_crm_workbook_imported/);
assert.match(api, /Import up to 1,000 shippers per file/);
assert.match(api, /Duplicate domain in this import/);
assert.match(api, /shipper_base_imported/);
assert.match(api, /buildShipperDuplicateCandidates/);
assert.match(api, /canonicalShipperDuplicateDomain/);
assert.match(api, /canonicalShipperDuplicateName/);
assert.match(api, /Confirm the duplicate consolidation before saving/);
assert.match(api, /merged_into_shipper_id/);
assert.match(api, /shipper_accounts_merged/);
assert.match(api, /\.neq\("status", "archived"\)/);
assert.match(api, /\.eq\("shipper_id", duplicateId\)/);
assert.match(api, /\.update\(\{ shipper_id: primaryId, updated_at: now \}\)/);
assert.match(api, /normalizeShipper\(input, true\)/);
assert.match(api, /\.eq\("owner_email", user\.owner_email\)\.in\("domain", domainChunk\)/);
assert.match(service, /export async function importShippers/);
assert.match(service, /"import_shippers"/);
assert.match(service, /export async function importShipperCrmWorkbook/);
assert.match(service, /"import_shipper_crm_workbook"/);
assert.match(api, /Opportunity probability must be between 0 and 100/);
assert.match(api, /SHIPPER_ENUMS\.relationship_stage\.has\(relationshipStage\)/);
assert.match(api, /open_opportunity_count/);
assert.match(api, /active_rfi_count/);
assert.match(api, /pipelineCurrency === "mixed"/);
assert.match(api, /\.eq\("rfi_id", rfiId\)\.limit\(1\)/);
assert.match(api, /Promoted RFI/);
assert.match(api, /Moved shipper opportunity/);
assert.match(api, /Created RFx workspace from shipper opportunity/);
assert.match(api, /Complete the RFx demand snapshot and package before launching Bid Room/);
assert.match(api, /Closed opportunities cannot start a new RFx workspace/);
assert.match(api, /syncShipperOpportunityFromImplementationReadyAward/);
assert.match(api, /shipper_opportunity_won_from_rfx_award/);
assert.match(api, /markRfxAwardPackageImplementationReady/);
assert.match(api, /body\.action === "mark_rfx_award_package_implementation_ready"/);
assert.match(rfxService, /"mark_rfx_award_package_implementation_ready"/);
assert.match(rfxClient, /markRfxAwardPackageImplementationReady/);
assert.match(rfxClient, /data-rfx-action="mark-award-implementation-ready"/);
assert.match(api, /stage: "won"/);
assert.match(api, /probability: 100/);
assert.match(api, /Begin award implementation and commercial onboarding/);
assert.match(api, /if \(awardRow\.status === "implementation_ready"\)/);
assert.match(api, /shipper_opportunity_id: shipperOpportunity\?\.id \|\| null/);
assert.match(api, /const allowedFocus = new Set\(\["all", "needs_rfi", "rfi_due", "deal_due", "won", "lost"\]\)/);
assert.match(api, /won_opportunities/);
assert.match(api, /lost_opportunities/);
assert.match(api, /openOpportunityStages/);
assert.match(api, /Unknown shipper intelligence focus/);
assert.match(api, /shipper_account_actions/);
assert.match(api, /shipper_account_action_created/);
assert.match(api, /shipper_account_action_updated/);
assert.match(api, /shipper_account_action_deleted/);
assert.match(api, /SHIPPER_ACTION_PLAYBOOKS/);
assert.match(api, /shipperActionDueDate/);
assert.match(api, /shipper_account_playbook_applied/);
assert.match(api, /Unknown account action status/);
assert.match(api, /Unknown account action queue focus/);
assert.match(api, /shipper_account_action_status_updated/);
assert.match(api, /Profile, contact, and coverage are ready to engage/);
assert.match(api, /Add a working primary contact before outreach/);
assert.match(api, /Add declared lanes or quoted coverage/);
assert.match(api, /open_pipeline_value/);
assert.match(api, /\.eq\("owner_email", user\.owner_email\)\.eq\("id", rfiId\)\.single\(\)/);

for (const id of ["shipper-search", "shipper-table-body", "shipper-drawer", "shipper-pipeline", "shipper-pipeline-board", "shipper-commercial", "shipper-commercial-rfi-body", "shipper-commercial-opportunity-body", "shipper-commercial-won", "shipper-intelligence", "shipper-intelligence-search", "shipper-intelligence-focus", "shipper-intelligence-body", "refresh-shipper-intelligence", "shipper-import", "shipper-import-file", "shipper-import-preview", "confirm-shipper-import", "shipper-duplicates", "shipper-duplicates-list", "refresh-shipper-duplicates"]) {
  assert.match(page, new RegExp(`id="${id}"`));
}
for (const tab of ["overview", "contacts", "locations", "lanes", "rfis", "opportunities", "actions", "activity"]) {
  assert.match(page, new RegExp(`data-shipper-tab="${tab}"`));
}

assert.match(client, /window\.setTimeout\(\(\) => \{[\s\S]*?loadRows\(\{ reset: true \}\);[\s\S]*?\}, 280\)/);
assert.match(client, /fetchShipper\(id\)/);
assert.match(client, /fetchShipperAccountActivity/);
assert.match(client, /saveShipperRecord/);
assert.match(client, /deleteShipperRecord/);
assert.match(client, /archiveShippers/);
assert.match(client, /CHILD_FIELD_DEFAULTS/);
assert.match(client, /pageSize/);
assert.match(client, /RELATIONSHIP_STAGES/);
assert.match(client, /fetchShipperRelationshipPipeline/);
assert.match(client, /moveShipperRelationshipStage/);
assert.match(client, /data-pipeline-drop-stage/);
assert.match(client, /dragstart/);
assert.match(client, /pipelineReady/);
assert.match(client, /Mixed currencies/);
assert.match(client, /commercialReady/);
assert.match(client, /fetchShipperCommercialWork/);
assert.match(client, /fetchShipperIntelligence/);
assert.match(client, /loadShipperIntelligence/);
assert.match(client, /data-open-shipper/);
assert.match(client, /data-open-shipper-tab="actions"/);
assert.match(client, /Next actions/);
assert.match(client, /action_type: "follow_up"/);
assert.match(client, /applyShipperActionPlaybook/);
assert.match(client, /fetchShipperActionQueue/);
assert.match(client, /updateShipperAccountActionStatus/);
assert.match(client, /renderCadence/);
assert.match(client, /data-shipper-action-status/);
assert.match(client, /data-apply-shipper-playbook/);
assert.match(client, /Only missing open tasks are created/);
assert.match(client, /Ready to engage/);
assert.match(client, /promoteShipperRfiToOpportunity/);
assert.match(client, /moveShipperOpportunityStage/);
assert.match(client, /launchShipperOpportunityRfx/);
assert.match(client, /data-promote-shipper-rfi/);
assert.match(client, /data-launch-shipper-rfx/);
assert.match(client, /rfx-process\.html\?project=/);
assert.match(client, /rfx-events\.html\?rfx_event_id=/);
assert.match(client, /This RFI already has a commercial deal/);
assert.match(client, /won_opportunities/);
assert.match(client, /Commercial outcome/);
assert.match(client, /Commercial readiness/);
assert.match(client, /SHIPPER_XLSX_MODULE_URL/);
assert.match(client, /parseShipperImportFile/);
assert.match(client, /downloadShipperTemplate/);
assert.match(client, /confirmShipperImport/);
assert.match(client, /importShippers\(rows\)/);
assert.match(client, /importShipperCrmWorkbook/);
assert.match(client, /Relational workbook detected/);
assert.match(client, /SHIPPER_CRM_WORKBOOK_TEMPLATE/);
assert.match(client, /external_account_id/);
assert.match(client, /fetchShipperDuplicates/);
assert.match(client, /mergeShipperAccounts/);
assert.match(client, /loadShipperDuplicates/);
assert.match(client, /mergeDuplicateShippers/);
assert.match(client, /data-merge-shipper-primary/);
assert.match(client, /does not merge anything automatically/);
assert.match(client, /data-open-shipper-rfx-project/);
assert.match(client, /Closed outcome/);
assert.match(page, /value="won">Won \/ implementation/);
assert.match(page, /data-shipper-view="import"/);
assert.match(page, /data-shipper-view="duplicates"/);
assert.match(page, /data-shipper-view="intelligence"/);
assert.match(page, /data-shipper-view="cadence"/);
assert.match(page, /id="shipper-cadence"/);

assert.match(auth, /href: "\.\/shipper-crm\.html"/);
assert.match(auth, /"shipper-crm"/);
assert.match(styles, /\.shipper-table/);
assert.match(styles, /height: 30px/);
assert.match(styles, /\.shipper-drawer/);
assert.match(styles, /\.shipper-view-switcher/);
assert.match(styles, /\.shipper-pipeline-board/);
assert.match(styles, /\.shipper-commercial-grid/);
assert.match(styles, /\.shipper-commercial-table/);
assert.match(styles, /\.shipper-intelligence-table/);
assert.match(styles, /\.shipper-intelligence-health/);
assert.match(styles, /\.shipper-account-command/);
assert.match(styles, /\.shipper-activity-list/);
assert.match(styles, /\.shipper-import/);
assert.match(styles, /\.shipper-import-table/);
assert.match(styles, /\.shipper-duplicates/);
assert.match(styles, /\.shipper-duplicate-comparison/);
assert.match(styles, /\.shipper-action-playbooks/);
assert.match(styles, /\.shipper-cadence-table/);

console.log("Shipper CRM schema, API, isolation, and UI contracts passed.");
