import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {classifyBidCommandReplay,sanitizePrivateConnectorValue} from '../_shared/marksman-loads-bid-contract.ts';
import {MarksmanLoadsBidContractError} from '../_shared/marksman-loads-bid-contract.ts';
import {MARKSMAN_LOADS_PROVIDER,canBindFitCommandReadback,reconcileFitPayload,type VerifiedMarksmanLoadsFitRequest,verifyMarksmanLoadsFitRequest} from '../_shared/marksman-loads-fit-contract.ts';
import {decryptRfxInvitationToken} from '../_shared/rfx-invitation-token.ts';

const SUPABASE_URL=String(Deno.env.get('SUPABASE_URL')||'').trim().replace(/\/$/,'');
const SERVICE_KEY=String(Deno.env.get('RATEWARE_SUPABASE_SERVICE_ROLE_KEY')||'').trim();
const SECRET=String(Deno.env.get('MARKSMAN_LOADS_BID_CONNECTOR_SECRET')||'').trim();
const KEY_ID=String(Deno.env.get('MARKSMAN_LOADS_BID_CONNECTOR_KEY_ID')||'').trim();
const FIT_ENABLED=String(Deno.env.get('MARKSMAN_LOADS_FIT_CONNECTOR_ENABLED')||'').trim()==='true';
const INVITATION_KEY=String(Deno.env.get('RFX_INVITATION_TOKEN_ENCRYPTION_KEY')||Deno.env.get('RFX_RFI_LINK_ENCRYPTION_KEY')||Deno.env.get('GMAIL_TOKEN_ENCRYPTION_KEY')||'').trim();
const STALE_MS=2*60_000;
type RecordValue=Record<string,unknown>;

class FitError extends Error{code:string;status:number;details:RecordValue;constructor(message:string,code='RATEWARE_FIT_ERROR',status=400,details:RecordValue={}){super(message);this.name='FitError';this.code=code;this.status=status;this.details=details;}}
function object(value:unknown):RecordValue{return value&&typeof value==='object'&&!Array.isArray(value)?value as RecordValue:{};}
function text(value:unknown){return String(value==null?'':value).trim();}
function message(value:unknown){return(value instanceof Error?value.message:text(value)||'Private fit request failed.').slice(0,1000);}
function response(value:RecordValue,status=200,requestId=''){const headers=new Headers({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});if(requestId)headers.set('X-Request-Id',requestId);return new Response(JSON.stringify(sanitizePrivateConnectorValue(value)),{status,headers});}
function getClient(){if(!SUPABASE_URL||!SERVICE_KEY)throw new FitError('Rateware service connection is not configured.','FIT_CONNECTOR_NOT_CONFIGURED',503);return createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
type Client=ReturnType<typeof getClient>;

async function resolveContext(client:Client,verified:VerifiedMarksmanLoadsFitRequest){
  const body=verified.body;
  const link=await client.from('external_organization_links').select('organization_id,status,reviewed_at,reviewed_by_user_id,review_note').eq('provider',MARKSMAN_LOADS_PROVIDER).eq('external_organization_id',body.organizationId).eq('status','active').maybeSingle();
  if(link.error)throw link.error;if(!link.data||!link.data.reviewed_at||!text(link.data.reviewed_by_user_id)||!text(link.data.review_note))throw new FitError('No active reviewed organization link exists.','ORGANIZATION_LINK_NOT_REVIEWED',403);
  const workspaces=await client.from('workspace_registry').select('organization_id,organization_uuid').eq('organization_uuid',link.data.organization_id).limit(2);if(workspaces.error)throw workspaces.error;if(!workspaces.data||workspaces.data.length!==1)throw new FitError('Organization does not resolve to exactly one workspace.','WORKSPACE_LINK_AMBIGUOUS',409);
  const workspaceOrganizationId=text(workspaces.data[0].organization_id);
  const vendor=await client.from('vendors').select('id').eq('id',body.vendorId).eq('organization_id',workspaceOrganizationId).maybeSingle();if(vendor.error)throw vendor.error;if(!vendor.data)throw new FitError('Carrier vendor is outside this workspace.','VENDOR_LINK_MISMATCH',403);
  const event=await client.from('rfx_events').select('id').eq('id',body.eventId).eq('organization_id',workspaceOrganizationId).maybeSingle();if(event.error)throw event.error;if(!event.data)throw new FitError('Event is outside this workspace.','EVENT_LINK_MISMATCH',403);
  const lane=await client.from('rfx_lanes').select('id,rfx_segment_key').eq('id',body.laneId).eq('rfx_event_id',body.eventId).maybeSingle();if(lane.error)throw lane.error;if(!lane.data)throw new FitError('Lane is outside this event.','LANE_LINK_MISMATCH',403);
  const invitation=await client.from('rfx_lane_vendors').select('id,rfx_event_id,rfx_lane_id,vendor_id,invitation_status,invitation_token,invitation_token_encrypted').eq('id',body.invitationId).eq('vendor_id',body.vendorId).eq('rfx_event_id',body.eventId).eq('rfx_lane_id',body.laneId).maybeSingle();if(invitation.error)throw invitation.error;if(!invitation.data)throw new FitError('The signed carrier invitation scope does not exist.','PRIVATE_INVITATION_NOT_FOUND',404);
  if(!['invited','quoted','bid_submitted'].includes(text(invitation.data.invitation_status).toLowerCase()))throw new FitError('The invitation is not eligible for fit confirmation.','PRIVATE_INVITATION_INELIGIBLE',409);
  const segmentKey=verified.body.payload.confirmations[0].segment_key;if(text(lane.data.rfx_segment_key)&&text(lane.data.rfx_segment_key)!==segmentKey)throw new FitError('The fit segment does not match the selected lane.','FIT_SEGMENT_MISMATCH',409);
  return{externalOrganizationId:body.organizationId,canonicalOrganizationId:text(link.data.organization_id),workspaceOrganizationId,vendor:vendor.data as RecordValue,event:event.data as RecordValue,lane:lane.data as RecordValue,invitation:invitation.data as RecordValue};
}
function safeScope(context:Awaited<ReturnType<typeof resolveContext>>){return{status:'matched',resolverRef:context.invitation.id,externalOrganizationId:context.externalOrganizationId,organizationId:context.canonicalOrganizationId,workspaceOrganizationId:context.workspaceOrganizationId,vendor:{id:context.vendor.id},event:{id:context.event.id},lane:{id:context.lane.id},invitationStatus:context.invitation.invitation_status,credentialExposure:false};}

async function credential(invitation:RecordValue){const legacy=text(invitation.invitation_token);if(legacy)return legacy;if(!INVITATION_KEY)throw new FitError('Invitation credential decryption is not configured.','FIT_CONNECTOR_NOT_CONFIGURED',503);const value=await decryptRfxInvitationToken(invitation.invitation_token_encrypted,INVITATION_KEY);if(!value)throw new FitError('Private invitation has no recoverable credential.','PRIVATE_INVITATION_CREDENTIAL_MISSING',409);return value;}
async function currentRows(client:Client,verified:VerifiedMarksmanLoadsFitRequest){const result=await client.from('rfx_segment_confirmations').select('id,rfx_event_id,rfx_lane_vendor_id,vendor_id,segment_key,rubric_key,answer,comment,source,updated_at').eq('rfx_lane_vendor_id',verified.body.invitationId).eq('segment_key',verified.body.payload.confirmations[0].segment_key);if(result.error)throw result.error;return result.data||[];}
async function reconciliation(client:Client,verified:VerifiedMarksmanLoadsFitRequest,clock:()=>Date){const rows=await currentRows(client,verified),match=reconcileFitPayload(verified.body.payload,rows);return{status:match.matches?'reconciled':'reconcile_required',payloadMatches:match.matches,expectedCount:match.expectedCount,observedCount:match.observedCount,segmentKey:match.segmentKey,checkedAt:clock().toISOString()};}

async function findCommand(client:Client,verified:VerifiedMarksmanLoadsFitRequest){const byRequest=await client.from('marksman_loads_fit_commands').select('*').eq('provider',MARKSMAN_LOADS_PROVIDER).eq('request_id',verified.requestId).maybeSingle();if(byRequest.error)throw byRequest.error;if(byRequest.data)return byRequest.data as RecordValue;const byOperation=await client.from('marksman_loads_fit_commands').select('*').eq('provider',MARKSMAN_LOADS_PROVIDER).eq('operation_id',verified.body.operationId).maybeSingle();if(byOperation.error)throw byOperation.error;if(byOperation.data)return byOperation.data as RecordValue;const byPrepared=await client.from('marksman_loads_fit_commands').select('*').eq('provider',MARKSMAN_LOADS_PROVIDER).eq('prepared_receipt_id',verified.body.preparedReceiptId).maybeSingle();if(byPrepared.error)throw byPrepared.error;return byPrepared.data as RecordValue|null;}
async function createCommand(client:Client,verified:VerifiedMarksmanLoadsFitRequest,context:Awaited<ReturnType<typeof resolveContext>>){const body=verified.body;const insert=await client.from('marksman_loads_fit_commands').insert({provider:MARKSMAN_LOADS_PROVIDER,request_id:verified.requestId,request_fingerprint:verified.requestFingerprint,operation_id:body.operationId,prepared_receipt_id:body.preparedReceiptId,external_organization_id:body.organizationId,organization_id:context.canonicalOrganizationId,workspace_organization_id:context.workspaceOrganizationId,vendor_id:body.vendorId,rfx_event_id:body.eventId,rfx_lane_id:body.laneId,rfx_lane_vendor_id:body.invitationId,segment_key:body.payload.confirmations[0].segment_key,payload_fingerprint:body.payloadFingerprint,actor_id:body.humanConfirmation.actorId,actor_role:body.humanConfirmation.role,confirmed_at:body.humanConfirmation.confirmedAt,status:'received'}).select('*').single();if(!insert.error)return{command:insert.data as RecordValue,inserted:true};if(text(insert.error.code)!=='23505')throw insert.error;const existing=await findCommand(client,verified);if(!existing)throw insert.error;return{command:existing,inserted:false};}
async function updateCommand(client:Client,id:unknown,patch:RecordValue,clock:()=>Date){const result=await client.from('marksman_loads_fit_commands').update({...patch,updated_at:clock().toISOString()}).eq('id',id).select('*').single();if(result.error)throw result.error;return result.data as RecordValue;}

async function persistReceipt(client:Client,verified:VerifiedMarksmanLoadsFitRequest,context:Awaited<ReturnType<typeof resolveContext>>,command:RecordValue,fitReconciliation:RecordValue,clock:()=>Date){
  if(!canBindFitCommandReadback(command)||fitReconciliation.status!=='reconciled'||fitReconciliation.payloadMatches!==true)throw new FitError('Fit operation evidence is incomplete.','OPERATION_RECEIPT_INCOMPLETE',409);
  const values={provider:MARKSMAN_LOADS_PROVIDER,external_organization_id:verified.body.organizationId,organization_id:context.canonicalOrganizationId,workspace_organization_id:context.workspaceOrganizationId,vendor_id:verified.body.vendorId,rfx_event_id:verified.body.eventId,rfx_lane_id:verified.body.laneId,rfx_lane_vendor_id:verified.body.invitationId,effect:'fit',operation_id:verified.body.operationId,payload_fingerprint:verified.body.payloadFingerprint,segment_key:fitReconciliation.segmentKey,record_id:verified.body.invitationId,staging_record_id:null,source_command_id:null,source_fit_command_id:command.id,outcome:'committed',committed_at:clock().toISOString()};
  const columns='id,effect,operation_id,payload_fingerprint,segment_key,record_id,committed_at';const inserted=await client.from('marksman_loads_operation_receipts').insert(values).select(columns).single();if(!inserted.error)return inserted.data;
  if(text(inserted.error.code)!=='23505')throw inserted.error;const existing=await client.from('marksman_loads_operation_receipts').select(columns).eq('provider',MARKSMAN_LOADS_PROVIDER).eq('effect','fit').eq('operation_id',verified.body.operationId).maybeSingle();if(existing.error)throw existing.error;const row=object(existing.data);if(row.payload_fingerprint!==verified.body.payloadFingerprint||row.segment_key!==fitReconciliation.segmentKey||row.record_id!==verified.body.invitationId)throw new FitError('Existing fit receipt conflicts with this operation.','OPERATION_RECEIPT_CONFLICT',409);return row;
}

async function canonical(verified:VerifiedMarksmanLoadsFitRequest,context:Awaited<ReturnType<typeof resolveContext>>,fetchImpl:typeof fetch){const token=await credential(context.invitation);const result=await fetchImpl(`${SUPABASE_URL}/functions/v1/rfx-bid-api`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${SERVICE_KEY}`,'apikey':SERVICE_KEY,'X-Request-Id':verified.requestId},body:JSON.stringify({...verified.body.payload,token}),signal:AbortSignal.timeout(20_000),redirect:'error'});const raw=await result.text();let body:RecordValue={};try{body=object(raw?JSON.parse(raw):{});}catch{}if(!result.ok)throw new FitError(message(body.error)||`Canonical fit returned HTTP ${result.status}`,'CANONICAL_FIT_UNCERTAIN',409,{canonicalStatus:result.status});return sanitizePrivateConnectorValue(body) as RecordValue;}

async function existingCommand(client:Client,verified:VerifiedMarksmanLoadsFitRequest,context:Awaited<ReturnType<typeof resolveContext>>,command:RecordValue,clock:()=>Date){
  const equivalent=command.operation_id===verified.body.operationId&&command.prepared_receipt_id===verified.body.preparedReceiptId&&command.payload_fingerprint===verified.body.payloadFingerprint;const disposition=classifyBidCommandReplay(command,verified.requestFingerprint,clock().getTime(),STALE_MS,equivalent&&command.request_id!==verified.requestId);
  if(disposition==='idempotency_conflict')throw new FitError('Fit request identity conflicts with prior content.','IDEMPOTENCY_CONFLICT',409);if(disposition==='replay')return{...object(command.result),requestId:verified.requestId,originalRequestId:command.request_id,duplicate:true};if(disposition==='rejected')throw new FitError('This fit command was rejected.',text(command.error_code)||'COMMAND_REJECTED',409);if(disposition==='in_progress')throw new FitError('This fit command is already in progress.','COMMAND_IN_PROGRESS',409,{retryAfterSeconds:120});
  if(disposition==='resume_before_mutation'){const timestamp=clock().toISOString(),claimed=await client.from('marksman_loads_fit_commands').update({status:'executing',execution_started_at:timestamp,updated_at:timestamp}).eq('id',command.id).eq('status','received').select('*').maybeSingle();if(claimed.error)throw claimed.error;if(claimed.data)return{resumeExecution:true,command:claimed.data};throw new FitError('Fit command changed while being claimed.','COMMAND_IN_PROGRESS',409);}
  const fitReconciliation=await reconciliation(client,verified,clock);if(fitReconciliation.status==='reconciled'&&canBindFitCommandReadback(command)){const operationReceipt=await persistReceipt(client,verified,context,command,fitReconciliation,clock);const result={commandId:command.id,requestId:verified.requestId,status:'reconciled',effect:'rateware_save_fit',privateResolution:safeScope(context),reconciliation:fitReconciliation,operationReceipt,credentialExposure:false,externalExecution:true,ratewareFitSubmission:true,duplicate:true};await updateCommand(client,command.id,{status:'reconciled',result,error_code:null,error_detail:null,external_execution:true,rateware_fit_submission:true,reconciled_at:clock().toISOString()},clock);return result;}
  await updateCommand(client,command.id,{status:'reconcile_required',result:{...object(command.result),reconciliation:fitReconciliation},error_code:'RECONCILIATION_REQUIRED',error_detail:'Current fit rows do not prove that this operation committed.'},clock);throw new FitError('Previous fit execution is uncertain; it was not retried.','RECONCILIATION_REQUIRED',409,{reconciliation:fitReconciliation});
}

async function execute(client:Client,verified:VerifiedMarksmanLoadsFitRequest,context:Awaited<ReturnType<typeof resolveContext>>,fetchImpl:typeof fetch,clock:()=>Date){let{command,inserted}=await createCommand(client,verified,context);if(!inserted){const disposition=await existingCommand(client,verified,context,command,clock);if(!object(disposition).resumeExecution)return disposition;command=object(object(disposition).command);}else command=await updateCommand(client,command.id,{status:'executing',execution_started_at:clock().toISOString()},clock);
  let canonicalResult:RecordValue;try{canonicalResult=await canonical(verified,context,fetchImpl);}catch(error){const fitReconciliation=await reconciliation(client,verified,clock).catch(()=>null);await updateCommand(client,command.id,{status:'reconcile_required',result:fitReconciliation?{reconciliation:fitReconciliation}:null,error_code:error instanceof FitError?error.code:'CANONICAL_FIT_UNCERTAIN',error_detail:message(error),external_execution:true,rateware_fit_submission:false},clock);throw new FitError('Canonical fit did not return provable completion; no automatic retry will occur.','RECONCILIATION_REQUIRED',409,{reconciliation:fitReconciliation});}
  command=await updateCommand(client,command.id,{status:'submitted',result:{canonicalResult},external_execution:true,rateware_fit_submission:true},clock);const fitReconciliation=await reconciliation(client,verified,clock);if(fitReconciliation.status!=='reconciled'){await updateCommand(client,command.id,{status:'reconcile_required',result:{canonicalResult,reconciliation:fitReconciliation},error_code:'RECONCILIATION_REQUIRED',error_detail:'Fit response returned but current rows do not match.'},clock);throw new FitError('Fit returned but requires Rateware reconciliation.','RECONCILIATION_REQUIRED',409,{reconciliation:fitReconciliation});}
  const operationReceipt=await persistReceipt(client,verified,context,command,fitReconciliation,clock);const result={commandId:command.id,requestId:verified.requestId,status:'reconciled',effect:'rateware_save_fit',privateResolution:safeScope(context),canonicalResult,reconciliation:fitReconciliation,operationReceipt,authorizationEvidence:{algorithm:'HMAC-SHA256',keyId:verified.keyId,verified:true,requestExpiresAt:verified.expiresAt},credentialExposure:false,externalExecution:true,ratewareFitSubmission:true,duplicate:false};await updateCommand(client,command.id,{status:'reconciled',result,error_code:null,error_detail:null,reconciled_at:clock().toISOString()},clock);return result;
}

export function createRfxInternalFitHandler(dependencies:{getClient?:()=>Client;fetchImpl?:typeof fetch;fitEnabled?:boolean;sharedSecret?:string;keyId?:string;now?:()=>Date}={}){const clientFactory=dependencies.getClient||getClient,fetchImpl=dependencies.fetchImpl||fetch,enabled=dependencies.fitEnabled??FIT_ENABLED,sharedSecret=dependencies.sharedSecret??SECRET,keyId=dependencies.keyId??KEY_ID,now=dependencies.now||(()=>new Date());return async function handler(request:Request){let requestId='';try{if(request.method!=='POST')return response({error:'Method not allowed.',code:'METHOD_NOT_ALLOWED'},405);if(Number(request.headers.get('content-length')||0)>100_000)return response({error:'Request body is too large.',code:'REQUEST_TOO_LARGE'},413);const envelope=await request.json(),verified=await verifyMarksmanLoadsFitRequest(envelope,{sharedSecret,expectedKeyId:keyId,now:now()});requestId=verified.requestId;if(!enabled)throw new FitError('Private fit execution is disabled.','FIT_EXECUTION_DISABLED',503);const client=clientFactory(),context=await resolveContext(client,verified);return response(await execute(client,verified,context,fetchImpl,now),200,requestId);}catch(error){if(error instanceof MarksmanLoadsBidContractError||error instanceof FitError)return response({error:error.message,code:error.code,details:error instanceof FitError?error.details:{}},error.status,requestId);return response({error:message(error),code:'RATEWARE_FIT_ERROR'},500,requestId);}};}

Deno.serve(createRfxInternalFitHandler());
