-- Merge relationship rows that would otherwise violate unique constraints while
-- consolidating exact Carrier CRM duplicates. The canonical vendor is selected
-- by consolidate_exact_workspace_vendor_duplicates; this migration only makes
-- every dependent relationship safe to move.

create table if not exists public.vendor_merge_relationship_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  canonical_vendor_id uuid not null,
  duplicate_vendor_id uuid not null,
  relationship_type text not null,
  keeper_record_id uuid,
  merged_record_id uuid,
  action text not null default 'merged' check (action in ('merged', 'reassigned')),
  details jsonb not null default '{}'::jsonb
);

create index if not exists vendor_merge_relationship_audit_vendor_idx
  on public.vendor_merge_relationship_audit (canonical_vendor_id, duplicate_vendor_id, created_at desc);

create table if not exists public.rfx_ratebook_share_token_aliases (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  access_token_hash text not null,
  ratebook_share_id uuid not null references public.rfx_ratebook_shares(id) on delete cascade,
  source_share_id uuid,
  source_vendor_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  constraint rfx_ratebook_share_token_aliases_hash_unique unique (access_token_hash)
);

create index if not exists rfx_ratebook_share_token_aliases_share_idx
  on public.rfx_ratebook_share_token_aliases (ratebook_share_id);

comment on table public.rfx_ratebook_share_token_aliases is
  'Preserves previously issued private Ratebook links after an exact Carrier CRM duplicate is consolidated.';

alter table public.vendor_merge_relationship_audit enable row level security;
alter table public.rfx_ratebook_share_token_aliases enable row level security;

revoke all on public.vendor_merge_relationship_audit from anon, authenticated;
revoke all on public.rfx_ratebook_share_token_aliases from anon, authenticated;
grant select, insert on public.vendor_merge_relationship_audit to service_role;
grant select, insert, update, delete on public.rfx_ratebook_share_token_aliases to service_role;

create or replace function public.merge_exact_vendor_relationship_collisions(
  p_winner_id uuid,
  p_loser_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row record;
  v_keeper record;
  v_keeper_share record;
  v_loser_quote record;
  v_keeper_quote_id uuid;
  v_keeper_review_id uuid;
  v_merged_count integer := 0;
begin
  if p_winner_id is null or p_loser_id is null or p_winner_id = p_loser_id then
    raise exception 'A distinct canonical vendor and duplicate vendor are required.';
  end if;

  perform 1 from public.vendors where id in (p_winner_id, p_loser_id) order by id for update;

  -- Active Bid Room threads have a partial unique scope. Keep the canonical
  -- thread and move its complete message and source-reference history.
  for v_row in
    select t.*
    from public.bid_room_chat_threads t
    where t.vendor_id = p_loser_id
      and t.status <> 'archived'
    order by t.created_at, t.id
  loop
    select t.* into v_keeper
    from public.bid_room_chat_threads t
    where t.vendor_id = p_winner_id
      and t.rfx_event_id = v_row.rfx_event_id
      and t.thread_type = v_row.thread_type
      and t.rfx_lane_id is not distinct from v_row.rfx_lane_id
      and t.status <> 'archived'
    order by t.updated_at desc, t.id
    limit 1;

    if found then
      update public.bid_room_chat_messages
      set thread_id = v_keeper.id,
          vendor_id = p_winner_id
      where thread_id = v_row.id;

      update public.rfx_lane_vendors
      set bid_source_thread_id = v_keeper.id,
          updated_at = now()
      where bid_source_thread_id = v_row.id;

      update public.bid_room_chat_threads keeper
      set
        title = coalesce(nullif(keeper.title, ''), nullif(v_row.title, '')),
        google_chat_space = coalesce(nullif(keeper.google_chat_space, ''), nullif(v_row.google_chat_space, '')),
        google_chat_thread_key = coalesce(nullif(keeper.google_chat_thread_key, ''), nullif(v_row.google_chat_thread_key, '')),
        google_chat_thread_name = coalesce(nullif(keeper.google_chat_thread_name, ''), nullif(v_row.google_chat_thread_name, '')),
        google_chat_sync_status = case
          when lower(coalesce(keeper.google_chat_sync_status, '')) in ('synced', 'ready') then keeper.google_chat_sync_status
          else coalesce(nullif(v_row.google_chat_sync_status, ''), keeper.google_chat_sync_status)
        end,
        communication_status = case
          when coalesce(keeper.needs_reply, false) or coalesce(v_row.needs_reply, false) then 'needs_reply'
          when keeper.communication_status = 'open' or v_row.communication_status = 'open' then 'open'
          else 'resolved'
        end,
        needs_reply = coalesce(keeper.needs_reply, false) or coalesce(v_row.needs_reply, false),
        read_status = case when keeper.read_status = 'unread' or v_row.read_status = 'unread' then 'unread' else 'read' end,
        assigned_to = coalesce(nullif(keeper.assigned_to, ''), nullif(v_row.assigned_to, '')),
        internal_note = case
          when nullif(btrim(v_row.internal_note), '') is null then keeper.internal_note
          when nullif(btrim(keeper.internal_note), '') is null then v_row.internal_note
          when position(v_row.internal_note in keeper.internal_note) > 0 then keeper.internal_note
          else keeper.internal_note || E'\n' || v_row.internal_note
        end,
        last_read_at = greatest(keeper.last_read_at, v_row.last_read_at),
        resolved_at = greatest(keeper.resolved_at, v_row.resolved_at),
        resolved_by = coalesce(nullif(keeper.resolved_by, ''), nullif(v_row.resolved_by, '')),
        last_action_at = greatest(keeper.last_action_at, v_row.last_action_at),
        metadata = coalesce(v_row.metadata, '{}'::jsonb) || coalesce(keeper.metadata, '{}'::jsonb),
        updated_at = greatest(keeper.updated_at, v_row.updated_at, now())
      where keeper.id = v_keeper.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type,
        keeper_record_id, merged_record_id, details
      ) values (
        p_winner_id, p_loser_id, 'bid_room_chat_thread',
        v_keeper.id, v_row.id,
        jsonb_build_object('rfx_event_id', v_row.rfx_event_id, 'thread_type', v_row.thread_type, 'rfx_lane_id', v_row.rfx_lane_id)
      );

      delete from public.bid_room_chat_threads where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  -- A Ratebook can have only one private share per carrier. Preserve all old
  -- opaque links as aliases and merge quote, revision, review and delivery history.
  for v_row in
    select s.*
    from public.rfx_ratebook_shares s
    where s.vendor_id = p_loser_id
    order by s.created_at, s.id
  loop
    select s.* into v_keeper_share
    from public.rfx_ratebook_shares s
    where s.vendor_id = p_winner_id
      and s.ratebook_id = v_row.ratebook_id
    order by (s.status = 'active') desc, s.updated_at desc, s.id
    limit 1;

    if found then
      if nullif(btrim(v_row.access_token_hash), '') is not null then
        insert into public.rfx_ratebook_share_token_aliases (
          access_token_hash, ratebook_share_id, source_share_id, source_vendor_id, metadata
        ) values (
          v_row.access_token_hash,
          v_keeper_share.id,
          v_row.id,
          p_loser_id,
          jsonb_build_object('reason', 'exact_vendor_consolidation')
        )
        on conflict (access_token_hash) do update
        set ratebook_share_id = excluded.ratebook_share_id,
            source_share_id = excluded.source_share_id,
            source_vendor_id = excluded.source_vendor_id,
            metadata = coalesce(public.rfx_ratebook_share_token_aliases.metadata, '{}'::jsonb) || excluded.metadata;
      end if;

      update public.rfx_ratebook_share_token_aliases
      set ratebook_share_id = v_keeper_share.id,
          source_share_id = coalesce(source_share_id, v_row.id),
          source_vendor_id = coalesce(source_vendor_id, p_loser_id),
          metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('reason', 'exact_vendor_consolidation')
      where ratebook_share_id = v_row.id;

      for v_loser_quote in
        select q.*
        from public.rfx_ratebook_carrier_quotes q
        where q.ratebook_share_id = v_row.id
        order by q.created_at, q.id
      loop
        select q.id into v_keeper_quote_id
        from public.rfx_ratebook_carrier_quotes q
        where q.ratebook_share_id = v_keeper_share.id
          and q.package_lane_id = v_loser_quote.package_lane_id
        order by q.updated_at desc, q.id
        limit 1;

        if v_keeper_quote_id is null then
          update public.rfx_ratebook_carrier_quotes
          set ratebook_share_id = v_keeper_share.id,
              vendor_id = p_winner_id,
              updated_at = greatest(updated_at, now())
          where id = v_loser_quote.id;

          update public.rfx_ratebook_carrier_quote_revisions
          set ratebook_share_id = v_keeper_share.id,
              vendor_id = p_winner_id
          where quote_id = v_loser_quote.id;

          update public.rfx_ratebook_quote_reviews
          set vendor_id = p_winner_id,
              updated_at = greatest(updated_at, now())
          where quote_id = v_loser_quote.id;
        else
          select r.id into v_keeper_review_id
          from public.rfx_ratebook_quote_reviews r
          where r.quote_id = v_keeper_quote_id
          limit 1;

          if v_keeper_review_id is null then
            update public.rfx_ratebook_quote_reviews
            set quote_id = v_keeper_quote_id,
                vendor_id = p_winner_id,
                updated_at = greatest(updated_at, now())
            where quote_id = v_loser_quote.id;
          else
            update public.rfx_ratebook_quote_reviews keeper_review
            set
              decision = case
                when loser_review.updated_at >= keeper_review.updated_at then loser_review.decision
                else keeper_review.decision
              end,
              decision_note = case
                when nullif(btrim(loser_review.decision_note), '') is null then keeper_review.decision_note
                when nullif(btrim(keeper_review.decision_note), '') is null then loser_review.decision_note
                when position(loser_review.decision_note in keeper_review.decision_note) > 0 then keeper_review.decision_note
                else keeper_review.decision_note || E'\n' || loser_review.decision_note
              end,
              decided_at = greatest(keeper_review.decided_at, loser_review.decided_at),
              decided_by_email = case
                when loser_review.updated_at >= keeper_review.updated_at
                  then coalesce(nullif(loser_review.decided_by_email, ''), keeper_review.decided_by_email)
                else coalesce(nullif(keeper_review.decided_by_email, ''), loser_review.decided_by_email)
              end,
              metadata = coalesce(loser_review.metadata, '{}'::jsonb) || coalesce(keeper_review.metadata, '{}'::jsonb),
              updated_at = greatest(keeper_review.updated_at, loser_review.updated_at, now())
            from public.rfx_ratebook_quote_reviews loser_review
            where keeper_review.id = v_keeper_review_id
              and loser_review.quote_id = v_loser_quote.id;

            delete from public.rfx_ratebook_quote_reviews where quote_id = v_loser_quote.id;
          end if;

          update public.rfx_ratebook_carrier_quote_revisions
          set quote_id = v_keeper_quote_id,
              ratebook_share_id = v_keeper_share.id,
              vendor_id = p_winner_id
          where quote_id = v_loser_quote.id;

          update public.rfx_ratebook_carrier_quotes keeper_quote
          set
            status = case when loser_quote.updated_at >= keeper_quote.updated_at then loser_quote.status else keeper_quote.status end,
            all_in_rate = case when loser_quote.updated_at >= keeper_quote.updated_at then loser_quote.all_in_rate else keeper_quote.all_in_rate end,
            currency = case when loser_quote.updated_at >= keeper_quote.updated_at then loser_quote.currency else keeper_quote.currency end,
            weekly_capacity = case
              when loser_quote.updated_at >= keeper_quote.updated_at then coalesce(loser_quote.weekly_capacity, keeper_quote.weekly_capacity)
              else coalesce(keeper_quote.weekly_capacity, loser_quote.weekly_capacity)
            end,
            transit_days = case
              when loser_quote.updated_at >= keeper_quote.updated_at then coalesce(loser_quote.transit_days, keeper_quote.transit_days)
              else coalesce(keeper_quote.transit_days, loser_quote.transit_days)
            end,
            valid_until = case
              when loser_quote.updated_at >= keeper_quote.updated_at then coalesce(loser_quote.valid_until, keeper_quote.valid_until)
              else coalesce(keeper_quote.valid_until, loser_quote.valid_until)
            end,
            quote_reference = case
              when loser_quote.updated_at >= keeper_quote.updated_at then coalesce(nullif(loser_quote.quote_reference, ''), keeper_quote.quote_reference)
              else coalesce(nullif(keeper_quote.quote_reference, ''), loser_quote.quote_reference)
            end,
            notes = case
              when nullif(btrim(loser_quote.notes), '') is null then keeper_quote.notes
              when nullif(btrim(keeper_quote.notes), '') is null then loser_quote.notes
              when position(loser_quote.notes in keeper_quote.notes) > 0 then keeper_quote.notes
              else keeper_quote.notes || E'\n' || loser_quote.notes
            end,
            source = case when loser_quote.updated_at >= keeper_quote.updated_at then loser_quote.source else keeper_quote.source end,
            revision_number = greatest(keeper_quote.revision_number, loser_quote.revision_number),
            metadata = coalesce(loser_quote.metadata, '{}'::jsonb) || coalesce(keeper_quote.metadata, '{}'::jsonb),
            vendor_id = p_winner_id,
            updated_at = greatest(keeper_quote.updated_at, loser_quote.updated_at, now())
          from public.rfx_ratebook_carrier_quotes loser_quote
          where keeper_quote.id = v_keeper_quote_id
            and loser_quote.id = v_loser_quote.id;

          insert into public.vendor_merge_relationship_audit (
            canonical_vendor_id, duplicate_vendor_id, relationship_type,
            keeper_record_id, merged_record_id, details
          ) values (
            p_winner_id, p_loser_id, 'rfx_ratebook_carrier_quote',
            v_keeper_quote_id, v_loser_quote.id,
            jsonb_build_object('ratebook_share_id', v_row.id, 'package_lane_id', v_loser_quote.package_lane_id)
          );

          delete from public.rfx_ratebook_carrier_quotes where id = v_loser_quote.id;
          v_merged_count := v_merged_count + 1;
        end if;

        v_keeper_quote_id := null;
        v_keeper_review_id := null;
      end loop;

      update public.rfx_ratebook_carrier_quote_revisions
      set ratebook_share_id = v_keeper_share.id,
          vendor_id = p_winner_id
      where ratebook_share_id = v_row.id;

      update public.outreach_messages
      set ratebook_share_id = v_keeper_share.id,
          vendor_id = p_winner_id,
          updated_at = now()
      where ratebook_share_id = v_row.id;

      update public.rfx_ratebook_shares keeper_share
      set
        owner_user_id = coalesce(nullif(keeper_share.owner_user_id, ''), nullif(v_row.owner_user_id, '')),
        owner_email = coalesce(nullif(keeper_share.owner_email, ''), nullif(v_row.owner_email, '')),
        organization_id = coalesce(nullif(keeper_share.organization_id, ''), nullif(v_row.organization_id, '')),
        primary_rfx_lane_vendor_id = coalesce(keeper_share.primary_rfx_lane_vendor_id, v_row.primary_rfx_lane_vendor_id),
        status = case
          when keeper_share.status = 'active' or v_row.status = 'active' then 'active'
          when keeper_share.status = 'archived' or v_row.status = 'archived' then 'archived'
          else 'revoked'
        end,
        last_viewed_at = greatest(keeper_share.last_viewed_at, v_row.last_viewed_at),
        access_granted_at = coalesce(keeper_share.access_granted_at, v_row.access_granted_at),
        access_revoked_at = case
          when keeper_share.status = 'active' or v_row.status = 'active' then null
          else greatest(keeper_share.access_revoked_at, v_row.access_revoked_at)
        end,
        access_count = coalesce(keeper_share.access_count, 0) + coalesce(v_row.access_count, 0),
        last_accessed_at = greatest(keeper_share.last_accessed_at, v_row.last_accessed_at),
        last_quote_at = greatest(keeper_share.last_quote_at, v_row.last_quote_at),
        metadata = coalesce(v_row.metadata, '{}'::jsonb) || coalesce(keeper_share.metadata, '{}'::jsonb),
        updated_at = greatest(keeper_share.updated_at, v_row.updated_at, now())
      where keeper_share.id = v_keeper_share.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type,
        keeper_record_id, merged_record_id, details
      ) values (
        p_winner_id, p_loser_id, 'rfx_ratebook_share',
        v_keeper_share.id, v_row.id,
        jsonb_build_object('ratebook_id', v_row.ratebook_id, 'preserved_token_alias', nullif(btrim(v_row.access_token_hash), '') is not null)
      );

      delete from public.rfx_ratebook_shares where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  -- Vendor CI scorecards are one row per workspace/vendor. Keep the strongest
  -- evidence per metric and the highest relationship tier.
  for v_row in
    select s.*
    from public.vendor_value_scorecards s
    where s.vendor_id = p_loser_id
    order by s.created_at, s.id
  loop
    select s.* into v_keeper
    from public.vendor_value_scorecards s
    where s.vendor_id = p_winner_id
      and s.owner_email is not distinct from v_row.owner_email
    order by s.updated_at desc, s.id
    limit 1;

    if found then
      update public.vendor_value_scorecards keeper
      set
        owner_user_id = coalesce(nullif(keeper.owner_user_id, ''), nullif(v_row.owner_user_id, '')),
        tier = case greatest(
          case keeper.tier when 'collaborative' then 4 when 'strategic' then 3 when 'tactical' then 2 else 1 end,
          case v_row.tier when 'collaborative' then 4 when 'strategic' then 3 when 'tactical' then 2 else 1 end
        ) when 4 then 'collaborative' when 3 then 'strategic' when 2 then 'tactical' else 'watchlist' end,
        value_score = greatest(keeper.value_score, v_row.value_score),
        operational_score = greatest(keeper.operational_score, v_row.operational_score),
        commercial_score = greatest(keeper.commercial_score, v_row.commercial_score),
        financial_score = greatest(keeper.financial_score, v_row.financial_score),
        compliance_score = greatest(keeper.compliance_score, v_row.compliance_score),
        technology_score = greatest(keeper.technology_score, v_row.technology_score),
        relationship_score = greatest(keeper.relationship_score, v_row.relationship_score),
        attributes = coalesce(v_row.attributes, '{}'::jsonb) || coalesce(keeper.attributes, '{}'::jsonb),
        notes = case
          when nullif(btrim(v_row.notes), '') is null then keeper.notes
          when nullif(btrim(keeper.notes), '') is null then v_row.notes
          when position(v_row.notes in keeper.notes) > 0 then keeper.notes
          else keeper.notes || E'\n' || v_row.notes
        end,
        last_scored_at = greatest(keeper.last_scored_at, v_row.last_scored_at),
        updated_at = greatest(keeper.updated_at, v_row.updated_at, now())
      where keeper.id = v_keeper.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type, keeper_record_id, merged_record_id
      ) values (p_winner_id, p_loser_id, 'vendor_value_scorecard', v_keeper.id, v_row.id);

      delete from public.vendor_value_scorecards where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  -- WhatsApp contact identity is workspace + vendor + phone. Preserve the most
  -- restrictive contact state so a merge can never re-enable a blocked contact.
  for v_row in
    select c.*
    from public.vendor_whatsapp_contacts c
    where c.vendor_id = p_loser_id
    order by c.created_at, c.id
  loop
    select c.* into v_keeper
    from public.vendor_whatsapp_contacts c
    where c.vendor_id = p_winner_id
      and c.owner_email is not distinct from v_row.owner_email
      and c.phone_e164 = v_row.phone_e164
    order by c.updated_at desc, c.id
    limit 1;

    if found then
      update public.vendor_whatsapp_contacts keeper
      set
        owner_user_id = coalesce(nullif(keeper.owner_user_id, ''), nullif(v_row.owner_user_id, '')),
        contact_name = coalesce(nullif(keeper.contact_name, ''), nullif(v_row.contact_name, '')),
        label = coalesce(nullif(keeper.label, ''), nullif(v_row.label, '')),
        permission_basis = case
          when keeper.permission_basis = 'consent' or v_row.permission_basis = 'consent' then 'consent'
          when keeper.permission_basis = 'contractual' or v_row.permission_basis = 'contractual' then 'contractual'
          when keeper.permission_basis = 'manual' or v_row.permission_basis = 'manual' then 'manual'
          else 'unknown'
        end,
        do_not_contact = coalesce(keeper.do_not_contact, false) or coalesce(v_row.do_not_contact, false),
        is_primary = coalesce(keeper.is_primary, false) or coalesce(v_row.is_primary, false),
        status = case greatest(
          case keeper.status when 'blocked' then 4 when 'invalid' then 3 when 'inactive' then 2 else 1 end,
          case v_row.status when 'blocked' then 4 when 'invalid' then 3 when 'inactive' then 2 else 1 end
        ) when 4 then 'blocked' when 3 then 'invalid' when 2 then 'inactive' else 'active' end,
        source = coalesce(nullif(keeper.source, ''), nullif(v_row.source, '')),
        metadata = coalesce(v_row.metadata, '{}'::jsonb) || coalesce(keeper.metadata, '{}'::jsonb),
        updated_at = greatest(keeper.updated_at, v_row.updated_at, now())
      where keeper.id = v_keeper.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type, keeper_record_id, merged_record_id,
        details
      ) values (
        p_winner_id, p_loser_id, 'vendor_whatsapp_contact', v_keeper.id, v_row.id,
        jsonb_build_object('phone_e164', v_row.phone_e164)
      );

      delete from public.vendor_whatsapp_contacts where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  -- WhatsApp group identity follows the same expression as its unique index.
  for v_row in
    select g.*,
      coalesce(nullif(btrim(g.meta_group_id), ''), nullif(btrim(g.group_url), ''), nullif(btrim(g.group_name), '')) as group_identity
    from public.vendor_whatsapp_groups g
    where g.vendor_id = p_loser_id
    order by g.created_at, g.id
  loop
    select g.* into v_keeper
    from public.vendor_whatsapp_groups g
    where g.vendor_id = p_winner_id
      and g.owner_email is not distinct from v_row.owner_email
      and coalesce(nullif(btrim(g.meta_group_id), ''), nullif(btrim(g.group_url), ''), nullif(btrim(g.group_name), ''))
        is not distinct from v_row.group_identity
    order by g.updated_at desc, g.id
    limit 1;

    if found then
      update public.vendor_whatsapp_groups keeper
      set
        owner_user_id = coalesce(nullif(keeper.owner_user_id, ''), nullif(v_row.owner_user_id, '')),
        group_name = coalesce(nullif(keeper.group_name, ''), nullif(v_row.group_name, '')),
        group_url = coalesce(nullif(keeper.group_url, ''), nullif(v_row.group_url, '')),
        meta_group_id = coalesce(nullif(keeper.meta_group_id, ''), nullif(v_row.meta_group_id, '')),
        verification_status = case
          when keeper.verification_status = 'blocked' or v_row.verification_status = 'blocked' then 'blocked'
          when keeper.verification_status = 'error' or v_row.verification_status = 'error' then 'error'
          when keeper.verification_status = 'verified' or v_row.verification_status = 'verified' then 'verified'
          when keeper.verification_status = 'api_ready' or v_row.verification_status = 'api_ready' then 'api_ready'
          when keeper.verification_status = 'pending' or v_row.verification_status = 'pending' then 'pending'
          else 'manual_only'
        end,
        permission_basis = case
          when keeper.permission_basis = 'consent' or v_row.permission_basis = 'consent' then 'consent'
          when keeper.permission_basis = 'contractual' or v_row.permission_basis = 'contractual' then 'contractual'
          when keeper.permission_basis = 'manual' or v_row.permission_basis = 'manual' then 'manual'
          else 'unknown'
        end,
        do_not_contact = coalesce(keeper.do_not_contact, false) or coalesce(v_row.do_not_contact, false),
        last_verified_at = greatest(keeper.last_verified_at, v_row.last_verified_at),
        last_error = coalesce(nullif(keeper.last_error, ''), nullif(v_row.last_error, '')),
        metadata = coalesce(v_row.metadata, '{}'::jsonb) || coalesce(keeper.metadata, '{}'::jsonb),
        updated_at = greatest(keeper.updated_at, v_row.updated_at, now())
      where keeper.id = v_keeper.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type, keeper_record_id, merged_record_id,
        details
      ) values (
        p_winner_id, p_loser_id, 'vendor_whatsapp_group', v_keeper.id, v_row.id,
        jsonb_build_object('group_identity', v_row.group_identity)
      );

      delete from public.vendor_whatsapp_groups where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  -- Active suppressions are safety controls. Keep one active canonical row and
  -- merge the reason/evidence before deleting the duplicate relation.
  for v_row in
    select s.*
    from public.outreach_contact_suppressions s
    where s.vendor_id = p_loser_id
      and s.active is true
    order by s.created_at, s.id
  loop
    select s.* into v_keeper
    from public.outreach_contact_suppressions s
    where s.vendor_id = p_winner_id
      and s.active is true
      and s.owner_email = v_row.owner_email
      and s.channel = v_row.channel
      and s.contact_value = v_row.contact_value
    order by s.updated_at desc, s.id
    limit 1;

    if found then
      update public.outreach_contact_suppressions keeper
      set
        owner_id = coalesce(nullif(keeper.owner_id, ''), nullif(v_row.owner_id, '')),
        organization_id = coalesce(nullif(keeper.organization_id, ''), nullif(v_row.organization_id, '')),
        reason = case
          when position(v_row.reason in keeper.reason) > 0 then keeper.reason
          else keeper.reason || E'\n' || v_row.reason
        end,
        source = coalesce(nullif(keeper.source, ''), nullif(v_row.source, '')),
        metadata = coalesce(v_row.metadata, '{}'::jsonb) || coalesce(keeper.metadata, '{}'::jsonb),
        updated_at = greatest(keeper.updated_at, v_row.updated_at, now())
      where keeper.id = v_keeper.id;

      insert into public.vendor_merge_relationship_audit (
        canonical_vendor_id, duplicate_vendor_id, relationship_type, keeper_record_id, merged_record_id,
        details
      ) values (
        p_winner_id, p_loser_id, 'outreach_contact_suppression', v_keeper.id, v_row.id,
        jsonb_build_object('channel', v_row.channel, 'contact_value', v_row.contact_value)
      );

      delete from public.outreach_contact_suppressions where id = v_row.id;
      v_merged_count := v_merged_count + 1;
    end if;

  end loop;

  return jsonb_build_object('merged_relationship_collisions', v_merged_count);
end;
$$;

revoke all on function public.merge_exact_vendor_relationship_collisions(uuid, uuid) from public;
revoke all on function public.merge_exact_vendor_relationship_collisions(uuid, uuid) from anon;
revoke all on function public.merge_exact_vendor_relationship_collisions(uuid, uuid) from authenticated;
grant execute on function public.merge_exact_vendor_relationship_collisions(uuid, uuid) to service_role;

-- Patch the already-deployed consolidation function without copying its full
-- body. Remove the abort-only collision preflight and resolve each loser just
-- before the generic FK reassignment block.
do $patch$
declare
  v_definition text;
  v_conflict_start integer;
  v_group_loop_start integer;
  v_relation_anchor text := E'      update public.bid_room_chat_messages set vendor_id = v_loser.winner_id where vendor_id = v_loser.loser_id;';
begin
  select pg_get_functiondef(
    'public.consolidate_exact_workspace_vendor_duplicates(text,text,boolean,integer)'::regprocedure
  ) into v_definition;

  v_conflict_start := strpos(
    v_definition,
    E'  select count(*) into v_conflict_count\n  from (\n    select m.winner_id, t.rfx_event_id'
  );
  v_group_loop_start := strpos(v_definition, E'  for v_group in\n');

  if v_conflict_start = 0 or v_group_loop_start = 0 or v_group_loop_start <= v_conflict_start then
    raise exception 'Could not locate the vendor consolidation collision preflight block.';
  end if;

  v_definition := substring(v_definition from 1 for v_conflict_start - 1)
    || substring(v_definition from v_group_loop_start);

  if strpos(v_definition, v_relation_anchor) = 0 then
    raise exception 'Could not locate the vendor consolidation relationship update anchor.';
  end if;

  v_definition := replace(
    v_definition,
    v_relation_anchor,
    E'      perform public.merge_exact_vendor_relationship_collisions(v_loser.winner_id, v_loser.loser_id);\n\n'
      || v_relation_anchor
  );

  execute v_definition;
end;
$patch$;
