-- Provider Service Build 7: approval requests for bounded agent and human actions.
create table if not exists public.provider_approval_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  legal_entity_id uuid not null,
  legal_entity_code text not null,
  provider_relationship_id uuid,
  case_id uuid,
  action_proposal_id uuid,
  document_version_id uuid,
  approval_number bigint generated always as identity,
  approval_code text generated always as ('APR-' || legal_entity_code || '-' || lpad(approval_number::text, 6, '0')) stored,
  approval_mode text not null,
  action_code text not null,
  action_payload_snapshot jsonb not null default '{}'::jsonb,
  sensitivity text not null default 'internal',
  status text not null default 'requested',
  requested_by_actor_type text not null default 'user',
  requested_by_user_id text,
  requested_at timestamptz not null default now(),
  expires_at timestamptz,
  decided_by_user_id text,
  decided_at timestamptz,
  decision_note text,
  consumed_at timestamptz,
  correlation_id uuid not null default gen_random_uuid(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_approval_requests_org_id_unique unique (organization_id,id),
  constraint provider_approval_requests_org_rel_entity_unique unique (organization_id,id,provider_relationship_id,legal_entity_id),
  constraint provider_approval_requests_entity_fkey foreign key (organization_id,legal_entity_id,legal_entity_code) references public.legal_entities(organization_id,id,entity_code) on delete restrict,
  constraint provider_approval_requests_relationship_fkey foreign key (organization_id,provider_relationship_id,legal_entity_id) references public.provider_relationships(organization_id,id,legal_entity_id) on delete restrict,
  constraint provider_approval_requests_case_fkey foreign key (organization_id,case_id,provider_relationship_id,legal_entity_id) references public.provider_service_cases(organization_id,id,provider_relationship_id,legal_entity_id) on delete restrict,
  constraint provider_approval_requests_action_fkey foreign key (organization_id,action_proposal_id) references public.provider_agent_action_proposals(organization_id,id) on delete restrict,
  constraint provider_approval_requests_document_fkey foreign key (organization_id,document_version_id,provider_relationship_id,legal_entity_id) references public.provider_document_versions(organization_id,id,provider_relationship_id,legal_entity_id) on delete restrict,
  constraint provider_approval_requests_code_unique unique (organization_id,approval_code),
  constraint provider_approval_requests_entity_code_check check (legal_entity_code ~ '^[A-Z0-9]{2,16}$'),
  constraint provider_approval_requests_mode_check check (approval_mode in ('human','finance','legal','executive')),
  constraint provider_approval_requests_action_code_check check (action_code ~ '^[a-z][a-z0-9_]{1,127}$'),
  constraint provider_approval_requests_sensitivity_check check (sensitivity in ('public','internal','confidential','restricted','highly_restricted')),
  constraint provider_approval_requests_status_check check (status in ('requested','approved','rejected','expired','cancelled','consumed')),
  constraint provider_approval_requests_actor_check check (requested_by_actor_type in ('user','agent','system','integration')),
  constraint provider_approval_requests_scope_check check ((case_id is null and document_version_id is null) or provider_relationship_id is not null),
  constraint provider_approval_requests_decision_check check (status not in ('approved','rejected') or (decided_at is not null and nullif(btrim(coalesce(decided_by_user_id,'')),'') is not null)),
  constraint provider_approval_requests_separation_check check (decided_by_user_id is null or requested_by_user_id is null or decided_by_user_id <> requested_by_user_id),
  constraint provider_approval_requests_expiry_check check (expires_at is null or expires_at > requested_at),
  constraint provider_approval_requests_consumed_check check (status <> 'consumed' or consumed_at is not null)
);

create index if not exists provider_approval_requests_queue_idx on public.provider_approval_requests (organization_id,legal_entity_id,status,approval_mode,requested_at);
create index if not exists provider_approval_requests_relationship_idx on public.provider_approval_requests (provider_relationship_id,status,requested_at desc) where provider_relationship_id is not null;
